name: Create a Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  determine_version:
    name: Determine the next build version
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.echo_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: ./.github/release
      - id: determine_version
        name: Get Version
        run: npm run release -- --ci --release-version | tail -n 1 > RELEASE_VERSION
        working-directory: ./.github/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: echo_version
        run: echo "::set-output name=version::$(cat ./.github/release/RELEASE_VERSION)"
